default_stages: [pre-commit, pre-push]
default_language_version:
    python: python3.12

repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.5
    hooks:
      - id: ruff-format
      - id: ruff
        args: [--fix, --show-fixes, --exit-non-zero-on-fix]
        types_or: [python, pyi]
        require_serial: true
