default_stages: [pre-commit, pre-push]
default_language_version:
    python: python3.12

repos:
  - repo: local
    hooks:
      - id: ruff
        name: ruff
        entry: uvx ruff check src --fix --show-fixes
        types: [python]
        language: system
