services:
  migrations:
    build:
      context: ./
      dockerfile: ./docker/migrations.Dockerfile
    env_file:
      - .env
    networks:
      - dream_network

  db:
    image: postgres
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_store:/var/lib/postgresql/data
    networks:
      - dream_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-d $$POSTGRES_DB -U $$POSTGRES_USER" ]
      interval: 5s
      timeout: 60s
      retries: 5

volumes:
  pg_store:

networks:
  dream_network:
